import { Router, type IRouter } from "express";
import healthRouter from "./health";
import authRouter from "./auth";
import clientsRouter from "./clients";
import tasksRouter from "./tasks";
import timeRouter from "./time";
import leadsRouter from "./leads";
import invoicesRouter from "./invoices";
import usersRouter from "./users";
import reportsRouter from "./reports";
import notificationsRouter from "./notifications";
import automationsRouter from "./automations";
import stripeRouter from "./stripe";
import apikeysRouter from "./apikeys";
import externalRouter from "./external";
import auditRouter from "./audit";
import serviceRequestsRouter from "./service-requests";
import appNotificationsRouter from "./app-notifications";
import uploadsRouter from "./uploads";
import backupRouter from "./backup";

const router: IRouter = Router();

router.use(healthRouter);
router.use(authRouter);
router.use(clientsRouter);
router.use(tasksRouter);
router.use(timeRouter);
router.use(leadsRouter);
router.use(invoicesRouter);
router.use(usersRouter);
router.use(reportsRouter);
router.use(notificationsRouter);
router.use(automationsRouter);
router.use(stripeRouter);
router.use(apikeysRouter);
router.use(externalRouter);
router.use(auditRouter);
router.use(serviceRequestsRouter);
router.use(appNotificationsRouter);
router.use(uploadsRouter);
router.use(backupRouter);

export default router;
