import { Router, type IRouter } from "express";
import healthRouter from "./health";
import authRouter from "./auth";
import clientsRouter from "./clients";
import tasksRouter from "./tasks";
import timeRouter from "./time";
import leadsRouter from "./leads";
import invoicesRouter from "./invoices";
import recurringInvoicesRouter from "./recurring-invoices";
import remindersRouter from "./reminders";
import usersRouter from "./users";
import reportsRouter from "./reports";
import notificationsRouter from "./notifications";
import automationsRouter from "./automations";
import squareRouter from "./square";
import apikeysRouter from "./apikeys";
import externalRouter from "./external";
import auditRouter from "./audit";
import serviceRequestsRouter from "./service-requests";
import appNotificationsRouter from "./app-notifications";
import uploadsRouter from "./uploads";
import backupRouter from "./backup";
import servicesRouter from "./services";
import messagesRouter from "./messages";
import asanaRouter from "./asana";
import clickupRouter from "./clickup";
import contactRouter from "./contact";
import emailInboundRouter from "./email-inbound";
import missiveWebhookRouter from "./missive-webhook";
import zapierWebhookRouter from "./zapier-webhook";
import relayinboxWebhookRouter from "./relayinbox-webhook";
import estimateResponseRouter from "./estimate-response";
import payRouter from "./pay";
import transactionsRouter from "./transactions";
import onboardingRouter from "./onboarding";
import apRouter from "./ap";

const router: IRouter = Router();

router.use(healthRouter);
router.use(authRouter);
router.use(clientsRouter);
router.use(tasksRouter);
router.use(timeRouter);
router.use(leadsRouter);
router.use(invoicesRouter);
router.use(recurringInvoicesRouter);
router.use(remindersRouter);
router.use(usersRouter);
router.use(reportsRouter);
router.use(notificationsRouter);
router.use(automationsRouter);
router.use(squareRouter);
router.use(apikeysRouter);
router.use(externalRouter);
router.use(auditRouter);
router.use(serviceRequestsRouter);
router.use(appNotificationsRouter);
router.use(uploadsRouter);
router.use(backupRouter);
router.use(servicesRouter);
router.use(messagesRouter);
router.use(asanaRouter);
router.use(clickupRouter);
router.use(contactRouter);
router.use(emailInboundRouter);
router.use(missiveWebhookRouter);
router.use(zapierWebhookRouter);
router.use(relayinboxWebhookRouter);
router.use(estimateResponseRouter);
router.use(payRouter);
router.use(transactionsRouter);
router.use(onboardingRouter);
router.use(apRouter);

export default router;
