import { Router, type IRouter } from "express";
import { db } from "@workspace/db";
import { invoicesTable, clientsTable } from "@workspace/db";
import { eq } from "drizzle-orm";
import PDFDocument from "pdfkit";
import {
  ListInvoicesQueryParams,
  CreateInvoiceBody,
  UpdateInvoiceParams,
  UpdateInvoiceBody,
  DeleteInvoiceParams,
} from "@workspace/api-zod";
import { requireAdmin, requireAuth } from "../middleware/auth";

const router: IRouter = Router();

router.get("/invoices", requireAuth, async (req, res) => {
  const { clientId } = ListInvoicesQueryParams.parse(req.query);
  const user = req.session.user!;
  const effectiveClientId = user.role === "client" ? (user.client_id ?? undefined) : clientId;
  const rows = effectiveClientId
    ? await db.select().from(invoicesTable).where(eq(invoicesTable.client_id, effectiveClientId))
    : await db.select().from(invoicesTable);
  res.json(rows);
});

router.get("/invoices/:id/pdf", requireAuth, async (req, res) => {
  const id = Number(req.params["id"]);
  if (!id || isNaN(id)) {
    res.status(400).json({ error: "Invalid invoice id" });
    return;
  }

  const [row] = await db
    .select({
      id: invoicesTable.id,
      amount: invoicesTable.amount,
      status: invoicesTable.status,
      due_date: invoicesTable.due_date,
      description: invoicesTable.description,
      client_name: clientsTable.name,
      client_email: clientsTable.email,
    })
    .from(invoicesTable)
    .leftJoin(clientsTable, eq(invoicesTable.client_id, clientsTable.id))
    .where(eq(invoicesTable.id, id));

  if (!row) {
    res.status(404).json({ error: "Invoice not found" });
    return;
  }

  const fmtDate = (d: string) =>
    new Date(d + "T00:00:00").toLocaleDateString("en-US", {
      month: "long",
      day: "numeric",
      year: "numeric",
    });

  const fmtAmount = (n: number) =>
    n.toLocaleString("en-US", { style: "currency", currency: "USD" });

  const doc = new PDFDocument({ margin: 60, size: "LETTER" });

  res.setHeader("Content-Type", "application/pdf");
  res.setHeader(
    "Content-Disposition",
    `attachment; filename="invoice-${row.id}.pdf"`
  );

  doc.pipe(res);

  // ── Header ────────────────────────────────────────────────────────────
  doc.fontSize(24).font("Helvetica-Bold").text("INVOICE", { align: "left" });
  doc.moveDown(0.3);
  doc.fontSize(12).font("Helvetica").fillColor("#64748b")
    .text(`Invoice #${row.id}`, { align: "left" });
  doc.moveDown(1.5);

  // ── Client info ───────────────────────────────────────────────────────
  doc.fillColor("#000000").font("Helvetica-Bold").fontSize(11).text("Bill To");
  doc.font("Helvetica").fontSize(11)
    .text(row.client_name ?? "—")
    .text(row.client_email ?? "");
  doc.moveDown(1.5);

  // ── Divider ───────────────────────────────────────────────────────────
  doc.moveTo(60, doc.y).lineTo(552, doc.y).strokeColor("#e2e8f0").lineWidth(1).stroke();
  doc.moveDown(1);

  // ── Details table ─────────────────────────────────────────────────────
  const labelX = 60;
  const valueX = 220;
  const lineH = 22;

  const row_ = (label: string, value: string) => {
    const y = doc.y;
    doc.font("Helvetica-Bold").fontSize(10).fillColor("#64748b")
      .text(label, labelX, y, { width: 150 });
    doc.font("Helvetica").fontSize(10).fillColor("#000000")
      .text(value, valueX, y, { width: 300 });
    doc.y = y + lineH;
  };

  row_("Description", row.description || `Invoice #${row.id}`);
  row_("Amount", fmtAmount(row.amount));
  row_("Due Date", fmtDate(row.due_date));
  row_("Status", row.status.toUpperCase());
  doc.moveDown(1.5);

  // ── Divider ───────────────────────────────────────────────────────────
  doc.moveTo(60, doc.y).lineTo(552, doc.y).strokeColor("#e2e8f0").lineWidth(1).stroke();
  doc.moveDown(1);

  // ── Total ─────────────────────────────────────────────────────────────
  doc.font("Helvetica-Bold").fontSize(14).fillColor("#000000")
    .text("Total Due", labelX, doc.y, { width: 150, continued: false });
  doc.y -= doc.currentLineHeight() + 2;
  doc.font("Helvetica-Bold").fontSize(14)
    .text(fmtAmount(row.amount), valueX, doc.y, { width: 300 });
  doc.moveDown(3);

  // ── Footer ────────────────────────────────────────────────────────────
  doc.fontSize(9).fillColor("#94a3b8").font("Helvetica")
    .text("Generated by Flowstate", { align: "center" });

  doc.end();
});

router.post("/invoices", requireAdmin, async (req, res) => {
  const body = CreateInvoiceBody.parse(req.body);
  const [invoice] = await db.insert(invoicesTable).values(body).returning();
  res.status(201).json(invoice);
});

router.patch("/invoices/:id", requireAdmin, async (req, res) => {
  const { id } = UpdateInvoiceParams.parse(req.params);
  const body = UpdateInvoiceBody.parse(req.body);
  const [updated] = await db
    .update(invoicesTable)
    .set(body)
    .where(eq(invoicesTable.id, id))
    .returning();
  if (!updated) {
    res.status(404).json({ error: "Invoice not found" });
    return;
  }
  res.json(updated);
});

router.delete("/invoices/:id", requireAdmin, async (req, res) => {
  const { id } = DeleteInvoiceParams.parse(req.params);
  await db.delete(invoicesTable).where(eq(invoicesTable.id, id));
  res.status(204).send();
});

export default router;
