// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/invoicing/InvoicePage.tsx": () => import("../components/mockups/invoicing/InvoicePage.tsx"),
  "./components/mockups/login-vibes/NightModePro.tsx": () => import("../components/mockups/login-vibes/NightModePro.tsx"),
  "./components/mockups/login-vibes/QuietPrecision.tsx": () => import("../components/mockups/login-vibes/QuietPrecision.tsx"),
  "./components/mockups/login-vibes/TrustAnchor.tsx": () => import("../components/mockups/login-vibes/TrustAnchor.tsx")
};
